### ISSUE TITLE
Tenant Admin rights

### ISSUE THREAD

**Issue by wallandall** [SharePoint/sp-dev-provisioning-templates#54]
When adding Microsoft 365 learning pathway from https://lookbook.microsoft.com I get an error that I need to be Tenant Admin. The account I am using is a Global Admin so why am I getting this error. Additionally I  have confirmed the requirements for the App Store and language

The full error is listed below:

Provisioning could not be completed
The configuration of your tenant does not satisfy the requirements of the selected template.

Here are the details of missing prerequisites:

In order to provision the template you need Tenant Admin rights. Please ask a Tenant Admin to provision the template for you or to promote yourself to a Tenant Admin.
Please address the missing prerequisites, then try again.

**Comment by jansenbe** [comment]
This should have been fixed, please try again

**Comment by wallandall** [comment]
Thanks for the quick feedback, it looks like it is working
