### ISSUE TITLE
Provisioning start date for 2022

### ISSUE THREAD

**Issue by BlakeSweeting** [SharePoint/sp-dev-provisioning-templates#59]
Any date on when Provisioning will be available this year. 

I get the following message:

Provisioning is currently disabled due to a maintenance break.
We expect the service to be online again in January 2022.

**Comment by AltonPM** [comment]
Ditto!

**Comment by hvandesa** [comment]
Any updates?  Please?

**Comment by BlakeSweeting** [comment]
Any update?

**Comment by BlakeSweeting** [comment]
Someone who knows how, can you leave some step by step instructions on how to manually provision the templates please

**Comment by BlakeSweeting** [comment]
When provisioning any of the templates, I get "Unfortunately your site provisioning at least partially failed". A few people have also got this issue.
